package com.redhat.bfarr.solarvillage.businessprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "NEWORDER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "NEWORDER_ID_GENERATOR", sequenceName = "NEWORDER_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String firstName;

	private java.lang.String lastName;

	private java.util.Date dob;

	private java.lang.String addressLine1;

	private java.lang.String addressLine2;

	private java.lang.String postCode;

	private java.lang.Boolean memberOfHOA;

	private java.lang.String hoaName;

	public NewOrder() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.util.Date getDob() {
		return this.dob;
	}

	public void setDob(java.util.Date dob) {
		this.dob = dob;
	}

	public java.lang.String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(java.lang.String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public java.lang.String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(java.lang.String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public java.lang.String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(java.lang.String postCode) {
		this.postCode = postCode;
	}

	public java.lang.Boolean getMemberOfHOA() {
		return this.memberOfHOA;
	}

	public void setMemberOfHOA(java.lang.Boolean memberOfHOA) {
		this.memberOfHOA = memberOfHOA;
	}

	public java.lang.String getHoaName() {
		return this.hoaName;
	}

	public void setHoaName(java.lang.String hoaName) {
		this.hoaName = hoaName;
	}

	public NewOrder(java.lang.Long id, java.lang.String firstName,
			java.lang.String lastName, java.util.Date dob,
			java.lang.String addressLine1, java.lang.String addressLine2,
			java.lang.String postCode, java.lang.Boolean memberOfHOA,
			java.lang.String hoaName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.postCode = postCode;
		this.memberOfHOA = memberOfHOA;
		this.hoaName = hoaName;
	}

}